// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcMAjPXupzaxIh6q98Ulu1YUTYf96IPx0',
    appId: '1:998499343432:web:6e7c6028e498c4da938c7d',
    messagingSenderId: '998499343432',
    projectId: 'biodata-1f5cf',
    authDomain: 'biodata-1f5cf.firebaseapp.com',
    storageBucket: 'biodata-1f5cf.firebasestorage.app',
    measurementId: 'G-MST4C3J46C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOwNST0UswyQlntWubPJa1VNY42LLoUdM',
    appId: '1:998499343432:android:fa4d6a180a0682ec938c7d',
    messagingSenderId: '998499343432',
    projectId: 'biodata-1f5cf',
    storageBucket: 'biodata-1f5cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3aRhpcB9gT8d7HHZoyRBmZnJDs5VQfcw',
    appId: '1:998499343432:ios:ce8fe8c96d609272938c7d',
    messagingSenderId: '998499343432',
    projectId: 'biodata-1f5cf',
    storageBucket: 'biodata-1f5cf.firebasestorage.app',
    iosBundleId: 'com.latihan.biodata.biodata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3aRhpcB9gT8d7HHZoyRBmZnJDs5VQfcw',
    appId: '1:998499343432:ios:ce8fe8c96d609272938c7d',
    messagingSenderId: '998499343432',
    projectId: 'biodata-1f5cf',
    storageBucket: 'biodata-1f5cf.firebasestorage.app',
    iosBundleId: 'com.latihan.biodata.biodata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcMAjPXupzaxIh6q98Ulu1YUTYf96IPx0',
    appId: '1:998499343432:web:1394795eb8b0ab8b938c7d',
    messagingSenderId: '998499343432',
    projectId: 'biodata-1f5cf',
    authDomain: 'biodata-1f5cf.firebaseapp.com',
    storageBucket: 'biodata-1f5cf.firebasestorage.app',
    measurementId: 'G-L2JG35EJZW',
  );
}
